### ISSUE TITLE
Diminuir o ícone na tela de abertura (Splash Screen)

### ISSUE THREAD

**Issue by EduardoSpek** [matheuswr89/tabnews-app#1]
Olá Devs, recomendo diminuir o tamanho do ícone na tela de abertura. Atualmente está muito grande.

O que acha Matheus?

**Comment by matheuswr89** [comment]
Olá, obrigado pela primeira issue!

Eu estava com planos de diminuir o icon da Splash Screen, mas estava com um pouco de falta de tempo.

Mas ontem eu lancei uma nova versão na Playstore com a Splash Screen menor, como a imagem abaixo: 

![Screenshot_2023-07-22-14-10-06-712_com.tabnews.jpg](https://github.com/matheuswr89/tabnews-app/assets/44068234/813846af-9991-409a-ac42-ea8c03b0b12c)
