### ISSUE TITLE
Expandir o campo do editor de texto 

### ISSUE THREAD

**Issue by EduardoSpek** [matheuswr89/tabnews-app#2]
Olá Devs,

Recomendo expandir o campo do editor de texto. Atualmente está muito pequeno, deixando muito espaço vazio.

Recomendo se atentarem também em fazer o campo subir quando o teclado abrir, para que ele não sobreponha o campo de texto.

O que acha Matheus?

**Comment by matheuswr89** [comment]
Na parte de editor de texto pequeno você fala da tela do conteúdo ao responder um post ou comentário?

A respeito de levantar a view quando abrir o teclado, ontem eu lancei uma versão na Playstore que mitiga temporariamente o problema. Eu ainda tenho que ver uma forma melhor para isso.
